export const PROFIT_TYPE = {
  CREATE_GACHA: 'CREATE_GACHA',
  OPEN_LUCKY_BOX: 'OPEN_LUCKY_BOX',
  OPEN_SOCKET: 'OPEN_SOCKET',
  SELL_NFT: 'SELL_NFT',
  UPGRADE_NFT: 'UPGRADE_NFT',
  REPAIR_BED: 'REPAIR_BED',
  LEVEL_UP: 'LEVEL_UP',
  POST_MINTING: 'POST_MINTING',
  UN_STACKING: 'UN_STACKING',
  SPEED_UP: 'SPEED_UP'
}
